# Safety System Configuration - Performance Parameters
# Optimized for performance while maintaining safety

# Emergency Stop System Configuration
emergency_stop_system:
  max_response_time: 0.15         # Slightly relaxed response time
  min_distance_threshold: 0.25    # Smaller safety distance for performance
  enable_predictive_stop: true    
  emergency_timeout: 3.0          # Shorter emergency timeout

# Collision Detection Manager Configuration
collision_detection_manager:
  min_safe_distance: 0.25         # Smaller minimum safe distance
  critical_distance: 0.12         # Smaller critical distance
  time_horizon: 2.5               # Shorter prediction horizon
  confidence_threshold: 0.75      # Higher confidence threshold (less sensitive)
  update_rate: 15.0               # Lower update rate for performance

# Safety Fusion Manager Configuration
safety_fusion_manager:
  fusion_update_rate: 8.0         # Lower fusion rate
  health_check_timeout: 3.0       # Longer timeout (less sensitive)
  safety_margin_buffer: 0.05      # Smaller safety buffer
  decision_confidence_threshold: 0.7  # Lower confidence requirement

# Safety Command Arbiter Configuration
safety_command_arbiter:
  max_linear_velocity: 0.7        # Higher maximum speed
  max_angular_velocity: 2.5       # Higher maximum angular velocity
  safety_override_priority: 10    
  command_timeout: 0.8            # Longer command timeout
  enable_safety_limits: true      

# Safety Margins Configuration
safety_margins:
  following_distance: 1.5         # Shorter following distance
  lateral_clearance: 0.15         # Less lateral clearance
  intersection_clearance: 0.3     # Less intersection clearance
  emergency_brake_distance: 0.08  # Shorter emergency brake distance

# Risk Assessment Thresholds (performance optimized)
risk_thresholds:
  low_risk_distance: 0.8          
  medium_risk_distance: 0.5       
  high_risk_distance: 0.25        
  critical_risk_distance: 0.12    
  
  low_risk_ttc: 4.0               
  medium_risk_ttc: 2.5            
  high_risk_ttc: 1.2              
  critical_risk_ttc: 0.4          