distance_between_centers: 0.0125            # Distance between the centers of the dots, in meters
max_reproj_pixelerror_pose_estimation: 1.5  # Maximum tolerable reprojection error for pose estimation
virtual_stop_line_offset: 0.5               # Distance before the stop, in meters